import { TRAIL_STEPS_DEFAULT } from "../../diagnostics/sessionTrail";
import { GAME_LOG_LINE_MS, GAME_LOG_MAX_LINES } from "../../log/gameLogDefaults";
import { SEARCH_DEFAULTS } from "../../search/searchDefaults";
import type { ParameterSpec } from "../types";

/** The Settings tab: presets, saved settings, the app's own files and About. */
export const SETTINGS_TAB = "settings";
/** The Interface tab: the toolbar, theme, log and search. */
export const INTERFACE_TAB = "interface";
/** Performance debug, in the Renderer tab: what the performance HUD shows, and the tuners. */
const PERFORMANCE = { tab: "renderer", section: "performance" } as const;

export const TOOLBAR_BUTTONS = [
  ["help", "Help (?)", "the ? button that opens the controls help"],
  ["settings", "Settings (⚙)", "the ⚙ button that opens the Settings tab"],
  ["theme", "Theme", "the light and dark theme button"],
  ["inputMode", "Input method", "the input method button, which opens the Controls tab"],
] as const;

export const PERFORMANCE_HUD_METRICS = [
  ["fps", "FPS", true, "Frames per second rendered by the map."],
  ["frame", "Frame time", false, "Average time spent rendering each frame."],
  ["p95", "P95 frame time", false, "95th percentile frame time over the recent sample window."],
  ["activeMeshes", "Active meshes (#⬟)", false, "Babylon meshes currently active in the scene."],
  ["drawCalls", "Draw calls", false, "GPU draw calls submitted for the current frame when the renderer exposes them."],
  ["tiles", "Map tiles (#/#t)", false, "Visible map tiles over active map tiles managed by the tile runtime."],
  ["culling", "Culling", false, "Visible tracked objects over total tracked objects after hemisphere culling."],
  ["memory", "Memory", true, "Approximate JavaScript heap memory currently used by the page."],
] as const;

function toggle(id: string, label: string, description: string, fallback: boolean, reason: string, home: { tab: string; section: string }, source: string, level: "main" | "all" = "main"): ParameterSpec {
  return {
    id,
    label,
    description,
    unit: "none",
    kind: "boolean",
    default: fallback,
    defaultReason: reason,
    home: { ...home, level },
    appliesLive: true,
    source,
  };
}

function metres(id: string, label: string, description: string, fallback: number, min: number, max: number, source: string): ParameterSpec {
  return {
    id,
    label,
    description,
    unit: "m",
    kind: "number",
    bounds: () => ({ min, max }),
    scale: "log2",
    default: fallback,
    defaultReason: "The value it was drawn with before it became a setting.",
    home: { ...PERFORMANCE, level: "all" },
    appliesLive: true,
    source,
  };
}

export const INTERFACE_PARAMETERS: readonly ParameterSpec[] = [
  {
    id: "app.keepFiles",
    label: "Keep the app's files",
    description: "Keeps the app's own files on this device once they have been downloaded, so a later visit starts without asking the network for them, however long ago the last one was. Each file's name carries its content, so a kept file is never out of date: a new version of the app has new names, which are downloaded once, and the old files go. The page itself always comes from the network. Off forgets them and leaves the app to the browser's own cache. Scene images are kept apart: Scenes → Saved images.",
    unit: "none",
    kind: "boolean",
    default: true,
    defaultReason: "GitHub Pages lets the browser keep a file for ten minutes. On a visit to the UMN tour eleven minutes after the last, the browser asked for every file of the app again, and 1.55 of its 1.72 MiB came again in full (docs/proposals/panorama-scenes.md, \"Loading once\").",
    home: { tab: SETTINGS_TAB, section: "app-files", level: "main" },
    appliesLive: true,
    source: "src/app/appFiles.ts",
  },
  {
    id: "diagnostics.trail",
    label: "Remember how a visit ended",
    description: "Keeps each visit's steps on this device: what loaded, the log's lines, warnings, errors and the 360 image entered. A page that a browser stops, as a phone does to one that takes too much memory, runs nothing as it goes, so these steps are how the next visit can say that it happened and the report what it was doing. Nothing is sent anywhere. Off removes this visit's steps from the device; this visit's report still has them.",
    unit: "none",
    kind: "boolean",
    default: true,
    defaultReason: "On 2026-10-03 the UMN tour kept crashing on an iPhone, and nothing said what it had been doing, on which renderer, or which version of the app it was (docs/diagnostics.md).",
    home: { tab: SETTINGS_TAB, section: "diagnostics", level: "main" },
    appliesLive: true,
    source: "src/diagnostics/sessionTrail.ts",
  },
  {
    id: "diagnostics.trailSteps",
    label: "Steps kept",
    description: "How many of a visit's latest steps are held for its report and kept for the next visit. A step is one line of at most 300 characters; the same line again is counted, not added.",
    unit: "count",
    kind: "number",
    bounds: () => ({ min: 10, max: 1000 }),
    step: 0.05,
    scale: "log2",
    default: TRAIL_STEPS_DEFAULT,
    defaultReason: "Opening an example scene and entering its 360 image is 15 steps (docs/diagnostics.md), so 80 hold a visit of many images, with each kind of trouble as one step however often it comes. They are 24 KB at most, written to this device as a step is added.",
    home: { tab: SETTINGS_TAB, section: "diagnostics", level: "main" },
    appliesLive: true,
    source: "src/diagnostics/sessionTrail.ts",
  },
  {
    id: "interface.theme",
    label: "Theme",
    description: "Light or dark panels and toolbar.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "dark", label: "Dark" },
      { id: "light", label: "Light" },
    ],
    default: "dark",
    defaultReason: "A dark frame keeps attention on the map.",
    home: { tab: INTERFACE_TAB, section: "toolbar", level: "all" },
    appliesLive: true,
    source: "src/theme/theme.ts",
  },
  ...TOOLBAR_BUTTONS.map(([button, label, what]) => toggle(
    `interface.toolbar.${button}`, label, `Shows ${what}. Hiding it never hides what it opens: that stays under +.`,
    true, "A first-time visitor does not know that + opens the same things.", { tab: INTERFACE_TAB, section: "toolbar" }, "src/hud/hudButtonVisibility.ts",
  )),
  {
    id: "interface.log.lineDuration",
    label: "Log line time",
    description: "How long a finished line stays over the map before it fades. Opening the log shows every kept line again.",
    unit: "s",
    kind: "number",
    bounds: () => ({ min: 1, max: 600 }),
    step: 0.05,
    scale: "log2",
    default: GAME_LOG_LINE_MS / 1000,
    defaultReason: "Long enough to read a line twice, before this became a parameter.",
    home: { tab: INTERFACE_TAB, section: "log", level: "main" },
    appliesLive: true,
    source: "src/log/createGameLog.ts",
  },
  {
    id: "search.cacheDuration",
    label: "Keep search answers for",
    description: "How long a place or airport lookup's answer is kept in this page, so asking again reads it instead of asking the service. Kept in memory only; a reload forgets it.",
    unit: "h",
    kind: "number",
    bounds: () => ({ min: 0.01, max: 720 }),
    step: 0.05,
    scale: "log2",
    default: SEARCH_DEFAULTS.cacheHours,
    defaultReason: "A day, as the geocoder's usage policy asks answers to be cached.",
    home: { tab: INTERFACE_TAB, section: "search", level: "main" },
    appliesLive: true,
    source: "src/search/searchTuning.ts",
  },
  {
    id: "search.cacheEntries",
    label: "Search answers kept",
    description: "How many answers each lookup, places and airports, keeps; the oldest goes first.",
    unit: "count",
    kind: "number",
    bounds: () => ({ min: 1, max: 4096 }),
    step: 0.05,
    scale: "log2",
    default: SEARCH_DEFAULTS.cacheEntries,
    defaultReason: "What the place lookup kept before this became a parameter; the airport lookup kept 32.",
    home: { tab: INTERFACE_TAB, section: "search", level: "main" },
    appliesLive: true,
    source: "src/search/searchTuning.ts",
  },
  {
    id: "search.timeout",
    label: "Search timeout",
    description: "How long a place or airport lookup may take before it gives up and says so.",
    unit: "s",
    kind: "number",
    bounds: () => ({ min: 1, max: 300 }),
    step: 0.05,
    scale: "log2",
    default: SEARCH_DEFAULTS.timeoutSeconds,
    defaultReason: "What both lookups waited before this became a parameter.",
    home: { tab: INTERFACE_TAB, section: "search", level: "main" },
    appliesLive: true,
    source: "src/search/searchTuning.ts",
  },
  {
    id: "interface.log.maxLines",
    label: "Log lines kept",
    description: "How many lines the log keeps, newest first; older ones are dropped.",
    unit: "count",
    kind: "number",
    bounds: () => ({ min: 5, max: 2000 }),
    step: 0.05,
    scale: "log2",
    default: GAME_LOG_MAX_LINES,
    defaultReason: "What the log kept before this became a parameter.",
    home: { tab: INTERFACE_TAB, section: "log", level: "main" },
    appliesLive: true,
    source: "src/log/createGameLog.ts",
  },
  ...PERFORMANCE_HUD_METRICS.map(([metric, label, visible, tooltip]) => toggle(
    `interface.performanceHud.${metric}`, `${label} on the toolbar`, tooltip,
    visible, visible ? "Shown by default: it is the first thing to look at." : "Hidden by default: a debugging reading.", PERFORMANCE, "src/app/createGlobeApp.ts",
  )),
  toggle("interface.poiSpriteTuner", "POI sprite size tuner", "Shows the panel that tunes the size of point-of-interest sprites.",
    false, "A debugging panel.", PERFORMANCE, "src/hud/poiSpriteSizeTuner.ts"),
  toggle("interface.compassScaleTuner", "Compass scale tuner", "Shows the panel that tunes the orbit compass's size.",
    false, "A debugging panel.", PERFORMANCE, "src/hud/compassScaleTuner.ts"),
  {
    id: "visualization.compass.heightOffset",
    label: "Compass orbit height",
    description: "How far above the ground the orbit compass and the orbit target sit.",
    unit: "m",
    kind: "number",
    bounds: () => ({ min: -1000, max: 1000 }),
    step: 10,
    scale: "linear",
    default: 0,
    defaultReason: "On the ground under the orbit target.",
    home: { tab: "controls", section: "camera", level: "main" },
    appliesLive: true,
    source: "src/terrain/anchorHeight.ts",
  },
  {
    id: "visualization.compass.radiusScale",
    label: "Compass radius",
    description: "The orbit compass's radius as a share of the camera's distance.",
    unit: "ratio",
    kind: "number",
    bounds: () => ({ min: 0.001, max: 1 }),
    scale: "log2",
    default: 0.035,
    defaultReason: "The value it was drawn with before it became a setting.",
    home: { ...PERFORMANCE, level: "all" },
    appliesLive: true,
    source: "src/visualization/orbitCompass.ts",
  },
  metres("visualization.compass.minRadius", "Compass smallest radius", "The orbit compass never gets smaller than this.", 750, 1, 1_000_000, "src/visualization/orbitCompass.ts"),
  metres("visualization.compass.maxRadius", "Compass largest radius", "The orbit compass never gets larger than this.", 240_000, 1, 10_000_000, "src/visualization/orbitCompass.ts"),
  {
    id: "visualization.compass.labelSizeScale",
    label: "Compass label size",
    description: "The compass's letters as a share of its radius.",
    unit: "ratio",
    kind: "number",
    bounds: () => ({ min: 0.01, max: 2 }),
    scale: "log2",
    default: 0.16,
    defaultReason: "The value it was drawn with before it became a setting.",
    home: { ...PERFORMANCE, level: "all" },
    appliesLive: true,
    source: "src/visualization/orbitCompass.ts",
  },
  metres("visualization.poiSprite.maxSize", "POI sprite largest size", "Point-of-interest sprites never get larger than this.", 40_000, 1, 10_000_000, "src/hud/poiSpriteSizeTuner.ts"),
  metres("visualization.poiSprite.minSize", "POI sprite smallest size", "Point-of-interest sprites never get smaller than this.", 200, 1, 10_000_000, "src/hud/poiSpriteSizeTuner.ts"),
  metres("visualization.poiSprite.minRefZoom", "POI sprite near distance", "At this camera distance or closer, sprites are at their smallest.", 100, 1, 100_000_000, "src/hud/poiSpriteSizeTuner.ts"),
  metres("visualization.poiSprite.maxRefZoom", "POI sprite far distance", "At this camera distance or farther, sprites are at their largest.", 1_000_000, 1, 100_000_000, "src/hud/poiSpriteSizeTuner.ts"),
];
