import { DEFAULT_RASTER_BASE_MAP_ID, RASTER_BASE_MAP_SOURCES } from "../../engine/babylon/rasterBaseMaps";
import { TERRAIN_SOURCES } from "../../terrain/terrainTiles";
import {
  GOOGLE_DETAIL_STEP,
  GOOGLE_ERROR_TARGET_BOUNDS,
  RASTER_DETAIL_ENVELOPE,
  RASTER_DETAIL_STEP,
} from "../../terrain/mapDetailPolicy";
import type { ParameterSpec } from "../types";

/** The Map tab's sections, in order. */
export const MAP_TAB = "map";

export const MAP_SOURCE_PARAMETERS: readonly ParameterSpec[] = [
  {
    id: "map.source.basemap",
    label: "Basemap",
    description: "The map drawn on the globe: Google 3D Tiles with their own terrain, or a 2D basemap draped over the elevation provider.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "google", label: "Google 3D Tiles" },
      ...RASTER_BASE_MAP_SOURCES.map(source => ({ id: source.id, label: source.label })),
    ],
    default: DEFAULT_RASTER_BASE_MAP_ID,
    defaultReason: "USGS imagery with labels needs no key; an app with a Google key makes Google 3D Tiles the default.",
    home: { tab: MAP_TAB, section: "source", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/resolveMapRuntimeConfig.ts",
  },
  {
    id: "map.source.elevation",
    label: "Elevation provider",
    description: "Where 2D basemaps get their terrain heights. Google 3D Tiles bring their own.",
    unit: "none",
    kind: "choice",
    choices: TERRAIN_SOURCES.map(source => ({ id: source.id, label: source.label })),
    default: TERRAIN_SOURCES[0].id,
    defaultReason: "Mapterhorn serves global terrain without a key.",
    home: { tab: MAP_TAB, section: "source", level: "main" },
    appliesLive: true,
    source: "src/terrain/terrainTiles.ts",
  },
  {
    id: "map.source.googleKey",
    label: "Google Maps API key",
    description: "The key Google 3D Tiles are requested with. It is sent to Google only, and kept on this device.",
    unit: "none",
    kind: "text",
    default: "",
    defaultReason: "No key is built in; `?key=` gives one for a visit.",
    home: { tab: MAP_TAB, section: "source", level: "main" },
    appliesLive: false,
    source: "src/engine/babylon/createTilesRuntime.ts",
    sensitive: true,
  },
  {
    id: "map.source.cartoKey",
    label: "CARTO API key",
    description: "The key CARTO basemaps are requested with. It is sent to CARTO only, and kept on this device.",
    unit: "none",
    kind: "text",
    default: "",
    defaultReason: "No key is built in. Without one, CARTO answers with an \"API key required\" tile.",
    home: { tab: MAP_TAB, section: "source", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/rasterBaseMaps.ts",
    sensitive: true,
  },
];

const RASTER_BOUNDS = { min: RASTER_DETAIL_ENVELOPE.coarsest, max: RASTER_DETAIL_ENVELOPE.finest };
const GOOGLE_BOUNDS = { min: GOOGLE_ERROR_TARGET_BOUNDS.finest, max: GOOGLE_ERROR_TARGET_BOUNDS.coarsest };

export const MAP_DETAIL_PARAMETERS: readonly ParameterSpec[] = [
  {
    id: "map.detail.imagery.range",
    label: "2D imagery detail range",
    description: "The part of the scale the detail rail spans for 2D basemaps, in levels finer (+) or coarser (−) than Normal.",
    unit: "levels",
    kind: "range",
    bounds: () => RASTER_BOUNDS,
    step: RASTER_DETAIL_STEP,
    scale: "linear",
    track: { reversed: true, ramp: "detail" },
    default: { min: RASTER_DETAIL_ENVELOPE.coarsest, max: RASTER_DETAIL_ENVELOPE.finest },
    defaultReason: "Every offset the imagery selector supports.",
    home: { tab: MAP_TAB, section: "detail", level: "main" },
    appliesLive: true,
    source: "src/shell/mapDetailController.ts",
  },
  {
    id: "map.detail.imagery.default",
    label: "2D imagery default detail",
    description: "The detail 2D basemaps start at, in levels finer (+) or coarser (−) than Normal, where one image pixel covers about one screen pixel.",
    unit: "levels",
    kind: "number",
    named: [{ id: "normal", label: "Normal" }],
    bounds: () => RASTER_BOUNDS,
    step: RASTER_DETAIL_STEP,
    scale: "linear",
    track: { reversed: true, ramp: "detail" },
    default: "normal",
    defaultReason: "Normal: one image pixel on about one screen pixel.",
    home: { tab: MAP_TAB, section: "detail", level: "main" },
    appliesLive: true,
    source: "src/shell/mapDetailController.ts",
  },
  {
    id: "map.detail.google.range",
    label: "Google detail range",
    description: "The part of the scale the detail rail spans for Google 3D Tiles: the screen-space error the mesh may leave, in pixels. Smaller is finer and loads more.",
    unit: "px",
    kind: "range",
    bounds: () => GOOGLE_BOUNDS,
    step: GOOGLE_DETAIL_STEP,
    scale: "log2",
    track: { ramp: "detail" },
    default: { min: 4, max: 64 },
    defaultReason: "From 4 px, near the finest most devices sustain, to 64 px, where the mesh visibly coarsens.",
    home: { tab: MAP_TAB, section: "detail", level: "main" },
    appliesLive: true,
    source: "src/shell/mapDetailController.ts",
  },
  {
    id: "map.detail.google.default",
    label: "Google default detail",
    description: "The screen-space error Google 3D Tiles start at: a number of pixels, or a recommendation.",
    unit: "px",
    kind: "number",
    named: [
      { id: "renderer-default", label: "Recommended by the tiles renderer" },
      { id: "device-hints", label: "Recommended from this device's processor and memory" },
    ],
    bounds: () => GOOGLE_BOUNDS,
    step: GOOGLE_DETAIL_STEP,
    scale: "log2",
    track: { ramp: "detail" },
    default: "renderer-default",
    defaultReason: "The target Google's tiles plugin recommends, 20 px today.",
    home: { tab: MAP_TAB, section: "detail", level: "main" },
    appliesLive: true,
    source: "src/shell/mapDetailController.ts",
  },
  {
    id: "map.detail.imageryPath",
    label: "2D imagery path",
    description: "How 2D imagery is chosen and drawn: by its projected pixel size from a paged atlas, or one image per terrain tile.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "atlas", label: "Projected atlas" },
      { id: "legacy", label: "Per terrain tile" },
    ],
    default: "atlas",
    defaultReason: "Released with the evidence in validation/evidence/map-detail/; per-tile imagery is the rollback.",
    home: { tab: MAP_TAB, section: "detail", level: "all" },
    appliesLive: false,
    source: "src/engine/babylon/createRasterTilesRuntime.ts",
  },
  {
    id: "map.focus.refineFrom",
    label: "Refine Google mesh from",
    description: "The point Google 3D Tiles measure distance from when choosing mesh detail. What is visible is still decided by the camera.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "camera", label: "Camera" },
      { id: "focus", label: "Focus point" },
    ],
    default: "camera",
    defaultReason: "The camera is where the mesh is seen from.",
    home: { tab: MAP_TAB, section: "detail", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/createTilesRuntime.ts",
  },
];
