import type { ParameterSpec } from "../types";

export const RENDERER_TAB = "renderer";

export const RENDERER_PARAMETERS: readonly ParameterSpec[] = [
  {
    id: "renderer.backend",
    label: "Renderer",
    description: "The GPU interface that draws the globe. Auto-detect tries WebGPU and falls back to WebGL.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "auto", label: "Auto-detect" },
      { id: "webgpu", label: "WebGPU" },
      { id: "webgl2", label: "WebGL2" },
      { id: "webgl", label: "WebGL" },
    ],
    default: "auto",
    defaultReason: "WebGPU where it starts, otherwise the WebGL that last worked on this device.",
    home: { tab: RENDERER_TAB, section: "backend", level: "main" },
    appliesLive: false,
    source: "src/engine/babylon/createRendererMode.ts",
  },
  {
    id: "renderer.resolutionScale",
    label: "Resolution",
    description: "Pixels drawn per pixel of the display. Below 1 draws fewer and scales them up: softer, and less GPU work per frame.",
    unit: "ratio",
    kind: "number",
    bounds: () => ({ min: 0.25, max: 2 }),
    step: 0.25,
    scale: "log2",
    default: context => context.rendererDevicePixels === false
      ? { value: 1 / Math.max(1, context.devicePixelRatio), derivedFrom: "the safe WebGPU fallback, which draws a pixel per CSS pixel" }
      : { value: 1, derivedFrom: "a pixel drawn per pixel of the display" },
    defaultReason: "What the renderer drew before this became a parameter.",
    home: { tab: RENDERER_TAB, section: "frame", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/createBabylonRuntime.ts",
  },
  {
    id: "renderer.antialias",
    label: "Antialiasing",
    description: "Smooths the edges of the ground and models with several samples per pixel, where the renderer allows it. Off saves GPU memory and work.",
    unit: "none",
    kind: "boolean",
    default: true,
    defaultReason: "The renderer drew with it before this became a parameter; the safe WebGPU fallback turns it off.",
    home: { tab: RENDERER_TAB, section: "frame", level: "main" },
    appliesLive: false,
    source: "src/engine/babylon/createRendererMode.ts",
  },
  {
    id: "renderer.frameRateCap",
    label: "Frame rate cap",
    description: "The most frames drawn in a second. A lower cap saves power and heat; frames still come only when something changes.",
    unit: "fps",
    kind: "number",
    named: [{ id: "off", label: "Off" }],
    bounds: () => ({ min: 10, max: 240 }),
    step: 0.25,
    scale: "log2",
    default: "off",
    defaultReason: "No cap: as many frames as the display shows.",
    home: { tab: RENDERER_TAB, section: "frame", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/renderScheduler.ts",
  },
  {
    id: "renderer.clipping",
    label: "Depth range",
    description: "How the globe camera's nearest and farthest drawn distances are set: from its height each frame, or fixed. An app's own cameras, such as a cockpit's, keep theirs.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "automatic", label: "From the camera's height" },
      { id: "fixed", label: "Fixed" },
    ],
    default: "automatic",
    defaultReason: "Babylon's geospatial clipping keeps depth precise from the ground to orbit.",
    home: { tab: RENDERER_TAB, section: "clipping", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/createBabylonRuntime.ts",
  },
  {
    id: "renderer.clipping.fixed",
    label: "Fixed depth range",
    description: "The nearest and farthest distances drawn when the depth range is fixed. A wide range loses depth precision: far ground can flicker through near.",
    unit: "m",
    kind: "range",
    bounds: () => ({ min: 0.01, max: 1e9 }),
    step: 0.25,
    scale: "log2",
    default: { min: 1, max: 1e7 },
    defaultReason: "From a metre to past the far side of the Earth.",
    home: { tab: RENDERER_TAB, section: "clipping", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/createBabylonRuntime.ts",
  },
];
