import type { ParameterSpec } from "../types";

export const SKY_TAB = "sky";
/** The Date and time tab: the instant the Sun is placed for, which the Sky tab links to. */
export const TIME_TAB = "time";

/** The sky ladder's rungs, cheapest first. docs/proposals/sky.md says what each costs and what the next would add. */
export const SKY_MODELS = ["off", "lights", "dome"] as const;
export type SkyModel = (typeof SKY_MODELS)[number];

const EV = { id: "EV", text: "EV" } as const;
const LUMINANCE = { id: "cd/m2", text: "cd/m²" } as const;
const KILOMETRES = { id: "km", text: "km" } as const;
const RADIANCE = { id: "nW/(cm2 sr)", text: "nW/(cm² sr)" } as const;
const SOURCE = "src/engine/babylon/createSkyRuntime.ts";
const NIGHT_LIGHTS_SOURCE = "src/engine/babylon/createNightLights.ts";
const whenFixedTime = { id: "sky.time.mode", value: "fixed" } as const;

export const SKY_SECTION_TITLES: ReadonlyArray<readonly [string, string, string]> = [
  [TIME_TAB, "instant", "Date and time"],
  [SKY_TAB, "atmosphere", "Atmosphere and illumination"],
  [SKY_TAB, "night", "Moon and stars"],
  [SKY_TAB, "surface", "Ground"],
  [SKY_TAB, "nightLights", "Night lights"],
  [SKY_TAB, "exposure", "Exposure and display"],
];

/** Where the night lights come from, as GIBS asks to be acknowledged. */
export const NIGHT_LIGHTS_CREDIT = "Imagery from NASA's Global Imagery Browse Services (GIBS), part of NASA's Earth Science Data and Information System (ESDIS).";

/**
 * `sky.surface.lighting`'s third way, which an application may offer with
 * `settings.setChoices`: one factor for all imagery, the light on level
 * ground below the viewpoint. Right near the viewpoint and wrong far from
 * it, so a globe seen from afar is all day or all night; it saves a few
 * dozen operations a pixel for a low flight on a very slow device.
 */
export const VIEWPOINT_SURFACE_LIGHTING_CHOICE = {
  id: "viewpoint",
  label: "As at the viewpoint",
  description: "One factor for all imagery: the light on level ground below the viewpoint. Cheapest lit choice; right only near the viewpoint, so the planet from afar is all day or all night.",
} as const;

export const SKY_PARAMETERS: readonly ParameterSpec[] = [
  {
    id: "sky.time.mode",
    label: "Time",
    description: "Which instant the Sun is placed for: the device's clock, which moves the Sun as the day goes, or a set time, which never changes and so repeats a picture exactly. The Date and time tab's dials set it: Now follows the clock, and turning a dial or pressing a moment on it sets a time.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "now", label: "Now" },
      { id: "fixed", label: "A set time" },
    ],
    default: "now",
    defaultReason: "The sky as it is now over the place shown. A set time is for comparing pictures.",
    home: { tab: TIME_TAB, section: "instant", level: "main" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.time.date",
    label: "Date (UTC)",
    description: "The day of the set time, as year-month-day in Coordinated Universal Time. It decides how high the Sun climbs and how long the day is.",
    unit: "none",
    kind: "text",
    default: "2026-06-21",
    defaultReason: "The June solstice: a long day in the north, a short one in the south.",
    home: { tab: TIME_TAB, section: "instant", level: "main" },
    visibleWhen: whenFixedTime,
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.time.utcHours",
    label: "Time of day (UTC)",
    description: "The hour of the set time in Coordinated Universal Time, to the second, which is the same instant everywhere. The Date and time tab's dials show it as the solar time a sundial at the place shown reads, which is this plus four minutes for each degree east and the equation of time.",
    unit: "h",
    kind: "number",
    bounds: () => ({ min: 0, max: 24 }),
    step: 1 / 60,
    default: 18,
    defaultReason: "Midday in the central United States, where the globe starts.",
    home: { tab: TIME_TAB, section: "instant", level: "main" },
    visibleWhen: whenFixedTime,
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.model",
    label: "Sky model",
    description: "How much of the sky is computed and drawn. Off keeps the fixed background and fill light. Lights adds the Sun and the sky as physical lights and one background colour, with nothing drawn. Dome also draws the sky and the Sun's disc as one mesh whose colours are recomputed only when the Sun or the height changes.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "off", label: "Off", description: "The fixed background and relative fill light. No cost." },
      { id: "lights", label: "Lights", description: "A Sun light, a sky light and a background colour from the atmosphere model. Nothing more is drawn; 192 lines of sight through the model each time the Sun or the height changes." },
      { id: "dome", label: "Dome", description: "Lights, and the sky drawn as one mesh with a colour per vertex and no texture: one draw call a frame, and the dome's samples each time the Sun or the height changes." },
    ],
    default: "dome",
    defaultReason: "The planet lit as it is at that hour: day, twilight and night where they are, the Sun, the Moon, the stars and the sky drawn. Lights costs less; Off shows the map as photographed at any hour, for debugging and for devices too slow for the sky.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "main" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "renderer.ambientFillMultiplier",
    label: "Ambient fill multiplier",
    description: "With the sky model off, scales the runtime's hemispheric fill lights relative to their existing intensities. Zero removes this fill from lit surfaces. It does not change emissive imagery, the background, local lights or an application's emitters, and does not simulate night. A sky model replaces these lights with the Sun's and the sky's.",
    unit: "ratio",
    kind: "number",
    bounds: () => ({ min: 0, max: 4 }),
    step: 0.01,
    default: 1,
    defaultReason: "One preserves the existing relative lighting, including the simulation, Google tiles and fallback lights. Zero allows inspection without this uncalibrated ambient fill; four bounds deliberate over-lighting.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "main" },
    visibleWhen: { id: "sky.model", value: "off" },
    appliesLive: true,
    source: "src/engine/babylon/createBabylonRuntime.ts",
  },
  {
    id: "sky.atmosphere.aerosolOpticalDepth",
    label: "Haze",
    description: "The optical depth of aerosols looking straight up at 550 nm. More haze dims and reddens a low Sun, whitens the sky and brightens the glow around the Sun. Changing it rebuilds the atmosphere's tables.",
    unit: { id: "aod", text: "optical depth" },
    kind: "number",
    bounds: () => ({ min: 0, max: 1.5 }),
    step: 0.01,
    default: 0.1,
    defaultReason: "A clear day over land. 0.005 is the cleanest air on Earth; 0.5 is a heavy summer haze.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "main" },
    appliesLive: true,
    source: "src/sky/atmosphere.ts",
  },
  {
    id: "sky.night.luminance",
    label: "Night sky",
    description: "The luminance of the sky by its own light, added in every direction above the horizon and to the light on surfaces: airglow and the starlight of stars too faint to draw, or a city's glow. The Moon and the bright stars are added to it.",
    unit: LUMINANCE,
    kind: "number",
    bounds: () => ({ min: 0.00001, max: 1 }),
    step: 0.25,
    scale: "log2",
    default: 0.0002,
    defaultReason: "A moonless sky far from cities, about 22 magnitudes per square arc second: 0.0006 lux on level ground, where astronomical twilight ends. A full Moon gives about a hundred times as much light; a city's sky, 0.01 to 0.1 cd/m².",
    home: { tab: SKY_TAB, section: "night", level: "main" },
    appliesLive: true,
    source: "src/sky/skyState.ts",
  },
  {
    id: "sky.moon.mode",
    label: "Moon",
    description: "The Moon, placed by Meeus's lunar theory and lit by the Sun: its light on surfaces and the ground, by its phase and distance, through the air on its line of sight, and its disc with its phase. With Sky, the dome also draws the sky the Moon lights, when that is at least a hundredth of the sunlit sky's light.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "off", label: "Off", description: "No Moon: nights lit by the night sky alone, as before." },
      { id: "light", label: "Light and disc", description: "Its light and its disc; the sky its light scatters lights surfaces but is not drawn. One more sample." },
      { id: "sky", label: "Light, disc and sky", description: "Also the moonlit sky on the dome, at night: as many samples again as the dome takes." },
    ],
    default: "sky",
    defaultReason: "Nights as they are: a full Moon lights the ground a hundred times as much as the night sky, and brightens the sky around it.",
    home: { tab: SKY_TAB, section: "night", level: "main" },
    appliesLive: true,
    source: "src/sky/lunarPosition.ts",
  },
  {
    id: "sky.stars.mode",
    label: "Stars",
    description: "The stars of the Bright Star Catalogue at their places for the date, turned with the Earth, each its own brightness and colour, dimmed by the air on its line of sight and added to the sky. They show where the sky is dark enough at the exposure in use, and are neither downloaded nor drawn while none would show.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "off", label: "Off", description: "No stars." },
      { id: "catalogue", label: "Catalogue", description: "Up to 9,096 stars as one mesh, recomputed with the sky. Their catalogue, 196 kB and 135 kB compressed, is downloaded when the sky first gets dark enough for a star to show, and not by day." },
    ],
    default: "catalogue",
    defaultReason: "A night sky with its stars where they are; the Sky model's Dome draws them.",
    home: { tab: SKY_TAB, section: "night", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/createStarField.ts",
  },
  {
    id: "sky.stars.limitingMagnitude",
    label: "Faintest star",
    description: "Stars up to this visual magnitude are drawn; the catalogue holds stars to about 8. Each magnitude fainter is 2.5 times less light and about three times as many stars.",
    unit: { id: "mag", text: "mag" },
    kind: "number",
    bounds: () => ({ min: -1.5, max: 8.1 }),
    step: 0.1,
    default: 6.5,
    defaultReason: "The faintest a dark sky shows the eye: about 8,400 stars.",
    home: { tab: SKY_TAB, section: "night", level: "all" },
    visibleWhen: { id: "sky.stars.mode", value: "catalogue" },
    appliesLive: true,
    source: "src/sky/stars.ts",
  },
  {
    id: "sky.stars.sizePx",
    label: "Star size",
    description: "The square each star's light is spread over, px across. A star's light is the same at any size; a larger square spreads it, a smaller one saturates sooner.",
    unit: "px",
    kind: "number",
    bounds: () => ({ min: 1, max: 12 }),
    step: 0.5,
    default: 3,
    defaultReason: "A point a little wider than a pixel, so a star does not shimmer as the view turns.",
    home: { tab: SKY_TAB, section: "night", level: "all" },
    visibleWhen: { id: "sky.stars.mode", value: "catalogue" },
    appliesLive: true,
    source: "src/engine/babylon/createStarField.ts",
  },
  {
    id: "sky.stars.daylightAltitude",
    label: "Stars by day above",
    description: "By day near the ground the sky is far brighter than any star, and the exposure that shows the ground shows none. The sky thins with height, its brightness halving with each 5 km, and above the air it is black beside a sunlit planet. Between these two heights the stars' own exposure moves from the scene's, at the lower, to the darkest the metered range allows, at the upper, as metering on the sky behind them would; above the upper they show as on the darkest night, whatever lights the planet. Only the stars: the Sun, the Moon, the sky and the ground keep the scene's exposure. Two equal heights make a step at that height.",
    unit: KILOMETRES,
    kind: "range",
    bounds: () => ({ min: 0, max: 200 }),
    step: 1,
    default: { min: 0, max: 80 },
    defaultReason: "What metering on the model's daytime sky gives, within a few kilometres: Sirius shows from about 20 km, stars of the second magnitude from about 45 km, and the faintest drawn from 80 km. No aircraft flies that high; a view from space has its stars.",
    home: { tab: SKY_TAB, section: "night", level: "main" },
    visibleWhen: { id: "sky.stars.mode", value: "catalogue" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.atmosphere.groundAlbedo",
    label: "Ground albedo for the air",
    description: "The share of light the ground sends back up into the air, which brightens the sky a little, and the brightness of the ground the dome shows below the horizon where no map is drawn. Changing it rebuilds the atmosphere's tables.",
    unit: "fraction",
    kind: "number",
    bounds: () => ({ min: 0, max: 1 }),
    step: 0.01,
    default: 0.2,
    defaultReason: "Vegetated land. Open water is near 0.06, desert 0.35 and fresh snow 0.8.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "all" },
    appliesLive: true,
    source: "src/sky/atmosphere.ts",
  },
  {
    id: "sky.dome.zenithSamples",
    label: "Dome rows",
    description: "Rows of the dome's samples from straight up to straight down, crowded towards the horizon; nine more follow the Sun's height. More rows give a smoother horizon and cost more each time the dome is recomputed, and more triangles each frame.",
    unit: "count",
    kind: "number",
    bounds: () => ({ min: 8, max: 128 }),
    step: 1,
    default: 32,
    defaultReason: "A horizon band sampled every quarter of a degree at its closest, for about 1,400 samples: 2 to 3 ms on a laptop each time the Sun or the height changes.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "all" },
    appliesLive: true,
    source: "src/sky/skyState.ts",
  },
  {
    id: "sky.dome.azimuthSamples",
    label: "Dome columns",
    description: "Columns of the dome's samples from the Sun's bearing round to the opposite one, crowded towards the Sun; the other side mirrors them at no cost. More columns give a smoother glow around the Sun.",
    unit: "count",
    kind: "number",
    bounds: () => ({ min: 8, max: 128 }),
    step: 1,
    default: 32,
    defaultReason: "Columns a fifth of a degree apart beside the Sun, widening to eleven degrees opposite it, where the sky changes slowly.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "all" },
    appliesLive: true,
    source: "src/sky/skyState.ts",
  },
  {
    id: "sky.dome.integrationSteps",
    label: "Steps through the air",
    description: "Steps of the integration along each sample's line of sight. More steps follow the Earth's shadow and the haze layer more closely; each sample costs in proportion.",
    unit: "count",
    kind: "number",
    bounds: () => ({ min: 4, max: 96 }),
    step: 1,
    default: 16,
    defaultReason: "Within 8% of five hundred steps in every direction and at every Sun height tested, twilight included.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "all" },
    appliesLive: true,
    source: "src/sky/atmosphere.ts",
  },
  {
    id: "sky.update.sunAngle",
    label: "Recompute after the Sun moves",
    description: "How far the Sun may move in the sky, by the clock or by travel, before its light and the dome are computed again. With the clock running this also sets how often a frame is drawn for the sky alone: the Sun moves a quarter of a degree a minute.",
    unit: "deg",
    kind: "number",
    bounds: () => ({ min: 0.01, max: 5 }),
    step: 0.25,
    scale: "log2",
    default: 0.05,
    defaultReason: "A tenth of the Sun's own width: a step too small to see, one recomputation every twelve seconds while nothing else moves.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "all" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.update.densityChange",
    label: "Recompute after the air thins",
    description: "How much the air's density at the viewpoint may change with height before the sky is computed again: the haze layer's density below six kilometres, the air's above.",
    unit: "fraction",
    kind: "number",
    bounds: () => ({ min: 0.001, max: 0.5 }),
    step: 0.001,
    default: 0.02,
    defaultReason: "A 24 m climb near the ground and 160 m at altitude: a few recomputations a second in a steep climb.",
    home: { tab: SKY_TAB, section: "atmosphere", level: "all" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.surface.lighting",
    label: "Map imagery",
    description: "How a sky model lights map imagery the scene's lights do not reach: 2D map imagery, and any Google 3D Tile whose material comes unlit. By daylight takes it as the ground's reflectance under the Sun's, the Moon's and the sky's light on level ground at each point, by their height there, so the planet seen from afar has its day, twilight and night where they are. As photographed keeps it at its own brightness at any hour, as a map. Neither shades by slope.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "daylight", label: "By daylight", description: "Each pixel by the Sun's and the Moon's height at its place: for each of the two, an inverse sine, a table look-up and an exponential." },
      { id: "photograph", label: "As photographed", description: "The imagery's own brightness at any hour. No cost; for maps and debugging." },
    ],
    default: "daylight",
    defaultReason: "The ground darkens with the day where the day ends, as everything else does. It has no effect while the sky model is off.",
    home: { tab: SKY_TAB, section: "surface", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/imagery/terrainLightPlugin.ts",
  },
  {
    id: "sky.surface.albedoScale",
    label: "Imagery as reflectance",
    description: "The reflectance a pixel of unlit map imagery stands for, as a multiple of its linear value. A photograph already holds the Sun's light of the day it was taken, so this is a stand-in for measured reflectance, not a recovery of it.",
    unit: "ratio",
    kind: "number",
    bounds: () => ({ min: 0.1, max: 4 }),
    step: 0.05,
    default: 1.5,
    defaultReason: "A photograph of sunlit ground shows as itself again under a high Sun at the metered exposure, where a perfect white is two thirds of the display's.",
    home: { tab: SKY_TAB, section: "surface", level: "main" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.groundLight.mode",
    label: "Light from the ground",
    description: "Where the light lit surfaces receive from below comes from, such as an aircraft's underside. Off: none. Uniform: ground of the atmosphere's albedo under the Sun's, the Moon's and the sky's light, one colour for all ground. Rendered: the ground below as it is drawn, its own colours and every light on it, from a small image looking down, averaged as a surface facing down receives it.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "off", label: "Off", description: "No light from below. No cost; for comparing." },
      { id: "uniform", label: "Uniform", description: "The atmosphere's ground albedo under today's light. No cost beyond the sky's own." },
      { id: "rendered", label: "Rendered", description: "The ground below drawn into a few pixels and read back without waiting for the GPU, at the interval below." },
    ],
    default: "uniform",
    defaultReason: "On a globe the light from the ground reaches little but buildings' walls; an application with something to light from below, such as a flight, renders it.",
    home: { tab: SKY_TAB, section: "surface", level: "main" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.groundLight.probeSize",
    label: "Ground image size",
    description: "The side of the image the ground below is rendered into for its light. More pixels see smaller patches of the ground; the light is their weighted mean, so a few suffice.",
    unit: "px",
    kind: "number",
    bounds: () => ({ min: 2, max: 64 }),
    step: 1,
    default: 16,
    defaultReason: "256 pixels: patches a twentieth of the height across, finer than the colour of the light changes, and a read-back of one kilobyte.",
    home: { tab: SKY_TAB, section: "surface", level: "all" },
    visibleWhen: { id: "sky.groundLight.mode", value: "rendered" },
    appliesLive: true,
    source: "src/engine/babylon/createGroundLightProbe.ts",
  },
  {
    id: "sky.groundLight.probeInterval",
    label: "Ground image interval",
    description: "How often the ground below is rendered again while frames are drawn. A still view stops asking once the light stops changing.",
    unit: "s",
    kind: "number",
    bounds: () => ({ min: 0.05, max: 10 }),
    step: 0.25,
    scale: "log2",
    default: 0.5,
    defaultReason: "Twice a second: an aircraft crossing from field to water changes its underside within half a second, for one small render in thirty frames.",
    home: { tab: SKY_TAB, section: "surface", level: "all" },
    visibleWhen: { id: "sky.groundLight.mode", value: "rendered" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.groundLight.probeFieldOfView",
    label: "Ground image field of view",
    description: "How wide the image of the ground below is, about straight down. A surface facing down receives the rest from nearer the horizon, taken as the same.",
    unit: "deg",
    kind: "number",
    bounds: () => ({ min: 30, max: 150 }),
    step: 1,
    default: 120,
    defaultReason: "Three quarters of the light a surface facing down receives comes from within 60° of straight down; wider spends pixels on the horizon.",
    home: { tab: SKY_TAB, section: "surface", level: "all" },
    visibleWhen: { id: "sky.groundLight.mode", value: "rendered" },
    appliesLive: true,
    source: "src/engine/babylon/createGroundLightProbe.ts",
  },
  {
    id: "sky.nightLights.mode",
    label: "Night lights",
    description: `The light people put out at night, as the Day/Night Band of a VIIRS instrument saw it from orbit on one night: its radiance at each place, from lamps, in pixels about 750 m across. As light, it is the lamps' light on the ground, which lights the map's imagery where it falls; as the satellite's picture, it is the luminance the satellite saw, added to the imagery as it is. Tiles are downloaded only where the Sun is below the height set below on ground the viewpoint can see, from NASA's servers, which learn which parts of the world are looked at. ${NIGHT_LIGHTS_CREDIT}`,
    unit: "none",
    kind: "choice",
    choices: [
      { id: "off", label: "Off", description: "Nights lit by the Moon, the stars and the night sky alone. Nothing downloaded." },
      { id: "light", label: "Lamps' light", description: "The lamps' light on the ground at each pixel's place lights the map's own imagery: a texture read and a few dozen operations a pixel." },
      { id: "picture", label: "Satellite's picture", description: "The luminance the satellite saw, added to the imagery without lighting it: the night data itself, a glow in the satellite's own pixels. The same cost." },
    ],
    default: "light",
    defaultReason: "Towns and roads lit at night where they are, on the day's imagery. The satellite's picture shows the data itself; Off downloads nothing. It has no effect while the sky model is off or imagery is shown as photographed.",
    home: { tab: SKY_TAB, section: "nightLights", level: "main" },
    appliesLive: true,
    source: NIGHT_LIGHTS_SOURCE,
  },
  {
    id: "sky.nightLights.date",
    label: "Night of",
    description: "The night the lights are from, as year-month-day in UTC: the satellites' daily product, cloudy places filled from earlier nights and moonlight taken out, from 2018-01-05 for NOAA-20 and 2012-01-19 for Suomi NPP to a day or two ago, with gaps. Lights show as they were that night whatever date the sky is shown for. Where the Sun never sets that night, as near a pole in its summer, there are none.",
    unit: "none",
    kind: "text",
    default: "2025-09-21",
    defaultReason: "The September equinox of 2025: neither pole in its midnight Sun, so lights from 74° S to 82° N, and a day the satellites' data has been reprocessed for rather than one of the last few, quickly made, days.",
    home: { tab: SKY_TAB, section: "nightLights", level: "main" },
    appliesLive: true,
    source: NIGHT_LIGHTS_SOURCE,
  },
  {
    id: "sky.nightLights.colourTemperature",
    label: "Lamps' colour",
    description: "The lamps' correlated colour temperature, which their light and the satellite's picture are given as a black body's colour: high-pressure sodium near 2,000 K, white LEDs from 3,000 K to 4,000 K. The satellite's band has no colour, so this is the same everywhere.",
    unit: { id: "K", text: "K" },
    kind: "number",
    bounds: () => ({ min: 1700, max: 6500 }),
    step: 100,
    default: 3000,
    defaultReason: "Between sodium's orange and LEDs' white, as streets lit by both are.",
    home: { tab: SKY_TAB, section: "nightLights", level: "main" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.nightLights.satellite",
    label: "Night lights' satellite",
    description: "Which satellite's Day/Night Band the night lights are from. Both cross every place at about 1:30 at night.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "NOAA20", label: "NOAA-20", description: "From 2018." },
      { id: "SNPP", label: "Suomi NPP", description: "From 2012; more of its sensor's noise over dark ground." },
    ],
    default: "NOAA20",
    defaultReason: "On 2025-09-21, dark ground from 55° to 79° N read 0.06 to 0.10 nW/(cm² sr) in NOAA-20's tiles and 0.13 to 0.30 in Suomi NPP's: less noise to take for lamps.",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    appliesLive: true,
    source: NIGHT_LIGHTS_SOURCE,
  },
  {
    id: "sky.nightLights.floor",
    label: "Radiance of no lamps",
    description: "Radiance taken as no lamp's and subtracted everywhere first: the night sky's own airglow and the sensor's noise, which would otherwise light all land and sea a little. The tiles hold radiance to 38.2 nW/(cm² sr); brighter, as city centres are, is clipped to that.",
    unit: RADIANCE,
    kind: "number",
    bounds: () => ({ min: 0, max: 10 }),
    step: 0.05,
    default: 0.5,
    defaultReason: "95% to 98% of the world's pixels read less on 2025-09-21; and two 8,000-lumen street lamps in a pixel, the least the band detects (arXiv:2510.02977), read about this much.",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.nightLights.radiancePerEmittance",
    label: "Radiance per lamp light",
    description: "The radiance the satellite measures for each lumen a square metre of lamps puts out, k in the Otus 3 model (arXiv:2510.02977): how much of the lamps' light falls in the satellite's band, and how much buildings and trees hide. More means less light for the same radiance. A radiance R above the floor is lamps' light of π R / (k G) lux on ground of reflectance G, which the satellite sees at R / k cd/m².",
    unit: { id: "nW/(cm2 sr)/(lm/m2)", text: "nW/(cm² sr) per lm/m²" },
    kind: "number",
    bounds: () => ({ min: 100, max: 2000 }),
    step: 0.05,
    scale: "log2",
    default: 431,
    defaultReason: "The geometric mean of the two measurements Otus 3 adapts: 260 over the San Mateo Bridge's lamps, seen straight down, and 714 over Flagstaff. A clipped city centre is then lamps' light of 1.8 lux, seen at 0.09 cd/m².",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    appliesLive: true,
    source: "src/sky/nightLights.ts",
  },
  {
    id: "sky.nightLights.groundReflectance",
    label: "Lit ground's reflectance",
    description: "The reflectance of the ground under the lamps, which sends their light up to the satellite, G in Otus 3: the darker the ground, the more light the same radiance stands for. Imagery as bright as this is shown as bright as the satellite saw it.",
    unit: "fraction",
    kind: "number",
    bounds: () => ({ min: 0.02, max: 0.8 }),
    step: 0.01,
    default: 0.15,
    defaultReason: "Otus 3's value for France: asphalt, roofs and gardens together.",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    visibleWhen: { id: "sky.nightLights.mode", value: "light" },
    appliesLive: true,
    source: "src/sky/nightLights.ts",
  },
  {
    id: "sky.nightLights.sunBelow",
    label: "Download where the Sun is below",
    description: "Night light tiles are downloaded, kept on the GPU and read by the terrain's shader only where the Sun is below this height somewhere on them, on ground the viewpoint can see: elsewhere the Sun's and the sky's light is too much brighter than lamps' for theirs to show.",
    unit: "deg",
    kind: "number",
    bounds: () => ({ min: -18, max: 10 }),
    step: 0.5,
    default: 0,
    defaultReason: "Sunset: the ground still has hundreds of lux, a hundred times a city centre's lamps, and the tiles are in well before twilight falls to theirs, about 4° below.",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    appliesLive: true,
    source: "src/sky/nightLights.ts",
  },
  {
    id: "sky.nightLights.maxZoom",
    label: "Finest night light tiles",
    description: "The finest zoom of night light tiles downloaded. Each level is twice as fine and up to four times as many tiles for the same ground. Zoom 8, the finest served, is 611 m a pixel at the equator and 432 m at 45°; the satellite's own pixels are about 750 m across.",
    unit: "levels",
    kind: "number",
    bounds: () => ({ min: 0, max: 8 }),
    step: 1,
    default: 8,
    defaultReason: "All the detail there is.",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    appliesLive: true,
    source: "src/sky/nightLights.ts",
  },
  {
    id: "sky.nightLights.windowTiles",
    label: "Night light window",
    description: "Tiles across the square of night light tiles on the GPU, 256 KiB each, rounded to a power of two: the finest zoom whose square holds the ground to the horizon, with a tile to spare all round, below the viewpoint. More hold finer tiles from higher up. A new square is shown only when every tile it needs is here.",
    unit: "count",
    kind: "number",
    bounds: context => ({
      min: 2,
      max: Math.max(2, Math.min(16, 2 ** Math.floor(Math.log2((context.maxTextureSize ?? 4096) / 256)))),
      reason: "The texture's side, 256 px a tile, is at most the renderer's largest.",
    }),
    step: 1,
    scale: "log2",
    default: 8,
    defaultReason: "16 MiB. At 45° it holds zoom 8, finer than the satellite's pixels, below about 6 km, and zoom 7, about as fine as them, to about 24 km; from space, the whole world at zoom 3.",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    appliesLive: true,
    source: NIGHT_LIGHTS_SOURCE,
  },
  {
    id: "sky.nightLights.memory",
    label: "Night light tiles kept",
    description: "Night light tiles kept in memory once downloaded, 64 KiB each, so a view returning to them or changing zoom needs no download; those of the window shown or being made ready are kept beyond it. GIBS's answers may not be stored, so none outlives the page.",
    unit: "MiB",
    kind: "number",
    bounds: () => ({ min: 1, max: 512 }),
    step: 1,
    scale: "log2",
    default: 32,
    defaultReason: "512 tiles: eight windows' worth.",
    home: { tab: SKY_TAB, section: "nightLights", level: "all" },
    appliesLive: true,
    source: NIGHT_LIGHTS_SOURCE,
  },
  {
    id: "sky.exposure.mode",
    label: "Exposure",
    description: "How the scene's luminance becomes the display's brightness under a sky model. Metered reads the light falling at the viewpoint, as an incident-light meter does, and follows it within the range below. Fixed holds one exposure, for comparing pictures. Neither changes any source's luminance.",
    unit: "none",
    kind: "choice",
    choices: [
      { id: "metered", label: "Metered" },
      { id: "fixed", label: "Fixed" },
    ],
    default: "metered",
    defaultReason: "A scene that reads at noon and at dusk without a setting being touched. It has no effect while the sky model is off.",
    home: { tab: SKY_TAB, section: "exposure", level: "main" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.exposure.meterRange",
    label: "Metered range",
    description: "The exposures the meter may choose, at ISO 100. Light beyond the lower end leaves the scene dark, as night is; light beyond the upper end leaves it bright.",
    unit: EV,
    kind: "range",
    bounds: () => ({ min: -12, max: 20 }),
    step: 0.1,
    default: { min: 1, max: 16 },
    defaultReason: "From 5 lux, where civil twilight ends, to beyond full sunlight. At the lower end white is 2.4 cd/m², so a dull red glow shows while unlit ground stays black.",
    home: { tab: SKY_TAB, section: "exposure", level: "main" },
    visibleWhen: { id: "sky.exposure.mode", value: "metered" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.exposure.adaptation",
    label: "Adaptation",
    description: "How far the metered exposure follows the light down from that of a high Sun, in stops of exposure for each stop of light. One follows it all the way, as a camera does, so dusk looks as bright as noon and its sky glares; less leaves dusk and night darker than day, as eyes see them. The metered range still bounds it.",
    unit: "ratio",
    kind: "number",
    bounds: () => ({ min: 0, max: 1 }),
    step: 0.01,
    default: 0.75,
    defaultReason: "At sunset the ground shows at a third of its noon brightness and the glow is not blown out; a full Moon still shows its landscape at the range's lower end.",
    home: { tab: SKY_TAB, section: "exposure", level: "main" },
    visibleWhen: { id: "sky.exposure.mode", value: "metered" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "sky.exposure.ev100",
    label: "Fixed exposure",
    description: "The fixed exposure at ISO 100: the display's white is a luminance of 1.2 × 2^EV cd/m². About 15 suits full sunlight and 1 a night scene.",
    unit: EV,
    kind: "number",
    bounds: () => ({ min: -12, max: 20 }),
    step: 0.1,
    default: 9.7,
    defaultReason: "White at 1,000 cd/m², the reference emitters were shown against before exposure was calibrated.",
    home: { tab: SKY_TAB, section: "exposure", level: "main" },
    visibleWhen: { id: "sky.exposure.mode", value: "fixed" },
    appliesLive: true,
    source: SOURCE,
  },
  {
    id: "renderer.exposureEV",
    label: "Exposure compensation",
    description: "Brightens or darkens everything drawn through the shared image processing by a factor of two for each EV, after any sky model's exposure. It is relative: with the sky model off it is the only exposure there is. Shaders that encode their own output, such as panoramas', do not follow it.",
    unit: EV,
    kind: "number",
    bounds: () => ({ min: -16, max: 16 }),
    step: 0.1,
    default: 0,
    defaultReason: "Zero EV changes nothing. The range permits inspection of very dim and bright sources without changing their physical emission.",
    home: { tab: SKY_TAB, section: "exposure", level: "main" },
    appliesLive: true,
    source: "src/engine/babylon/createBabylonRuntime.ts",
  },
];
