/**
 * The sky's physics, with no renderer in it: where the Sun and the Moon are,
 * the Sun's solar day and year at a place, the light they and the sky give
 * through a clear atmosphere, the stars of the Bright Star Catalogue, the
 * night lights a satellite sees and the light they put on the ground, and the
 * photographic exposure that shows a luminance as white.
 * The runtime's `sky` draws from these;
 * an application uses them for its own sources and instruments.
 * docs/proposals/sky.md is the specification.
 */
export {
  ASTRONOMICAL_UNIT_METERS,
  DELTA_T_SECONDS,
  SPA_REFRACTION_CUTOFF_DEG,
  julianDayFromUtcMs,
  refractionFormulaDeg,
  solarEphemeris,
  solarPosition,
  spaRefractionDeg,
  sunDirectionFrom,
  type SolarEphemeris,
  type SolarPosition,
  type SolarPositionInput,
} from "./solarPosition";
export {
  DAY_PART_ELEVATIONS_DEG,
  dayLengthsHours,
  equationOfTimeMs,
  seasonInstants,
  solarClockMs,
  solarDay,
  solarDayStartMs,
  utcForSolarClockMs,
  type DayPart,
  type DayPartTimes,
  type Season,
  type SolarDay,
} from "./solarDay";
export {
  ATMOSPHERE,
  createAtmosphere,
  miePhase,
  rayleighPhase,
  type Atmosphere,
  type AtmosphereBuildInfo,
  type AtmosphereParameters,
  type Rgb,
} from "./atmosphere";
export {
  MOON_MEAN_DISTANCE_KM,
  MOON_RADIUS_KM,
  MOONLIGHT_TINT,
  SUN_MAGNITUDE_AT_1_AU,
  lunarEphemeris,
  lunarPosition,
  moonIlluminanceLux,
  moonMagnitude,
  moonViewFrom,
  type LunarEphemeris,
  type LunarPosition,
  type MoonView,
} from "./lunarPosition";
export {
  applyMatrix3,
  blackBodyTint,
  celestialToEcefMatrix,
  colourTemperatureK,
  decodeStarCatalogue,
  loadStarCatalogue,
  precessionMatrix,
  starDirections,
  starIlluminanceLux,
  starTint,
  type Matrix3,
  type StarCatalogue,
} from "./stars";
export {
  MERCATOR_MAX_LAT_DEG,
  NIGHT_LIGHT_SATELLITES,
  NIGHT_RADIANCE_CLIP,
  NIGHT_RADIANCE_UNITS,
  NIGHT_TILE_MAX_ZOOM,
  NIGHT_TILE_PIXELS,
  RADIANCE_BY_GREY,
  chooseNightWindow,
  horizonDistanceMeters,
  illuminancePerRadiance,
  isNightLightDate,
  luminancePerRadiance,
  mercatorSpan,
  mercatorXY,
  neededNightTiles,
  nightLightTileUrl,
  radianceAboveFloor,
  radianceOfGrey,
  type MercatorSpan,
  type NightLightPhotometry,
  type NightLightSatellite,
  type NightTile,
  type NightWindow,
} from "./nightLights";
export {
  GROUND_LIGHT_LEAST_SINE,
  GROUND_LIGHT_SAMPLES,
  GROUND_LIGHT_TABLE,
  PHOTOMETRY,
  adaptEv100,
  computeSkyIllumination,
  groundLightAt,
  groundLightTable,
  groundLightWeight,
  placeInSky,
  createSkyDomeGeometry,
  drawnRefractionDeg,
  ev100ForIlluminance,
  ev100ForWhiteLuminance,
  fillSkyDome,
  horizonDipDeg,
  luminance,
  observerAt,
  parseUtcDate,
  standardAtmosphere,
  starEv100,
  whiteLuminanceForEv100,
  type SkyDomeGeometry,
  type SkyDomeLayout,
  type SkyIllumination,
  type SkyIlluminationOptions,
  type SkyMoon,
  type SkyObserver,
  type SkyPlacement,
  type Vec3,
} from "./skyState";
